### ISSUE TITLE
Protocol defaults to N/A even when already configured.

### ISSUE THREAD

**Issue by thorsager** [freeacs/web#8]
Protocol defaults to 'N/A' under 'Unit Type Configuration' even if Protocol has been selected on the specific Unit Type.

This could cause the protocol to be updated to 'N/A' if 'Vendor' or 'Description' is changed, which in turn  _disables_ the TR-111 Kick functionality.

Note: This is NOT a major bug, but I just ran into it, and wanted to make a note..

Anyway thanks for the great work :+1:

**Comment by jarlah** [comment]
I will check this. Most likely a simple bug.

**Comment by jarlah** [comment]
aha ... the protocol is stored in database as TR069 which is wrong. It should be TR-069
+--------------+------------+----------------+-------------+-------------+----------+
| unit_type_id | matcher_id | unit_type_name | vendor_name | description | protocol |
+--------------+------------+----------------+-------------+-------------+----------+
|            1 | NULL       | Some Test      | NULL        | Test        | TR069    |
+--------------+------------+----------------+-------------+-------------+----------+

**Comment by jarlah** [comment]
Can be merged
